import Head from "next/head";
import AccessoriesSwiper from "./AccessoriesSwiper";
import Categories from "./Categories";
import Discover from "./Discover";
import LandingSection from "./LandingSection";
import LaptopsSwiper from "./LaptopsSwiper";
import Marketing from "./Marketing";
import SecondSection from "./SecondSection";
import type { NextPage } from "next";
import { api } from "~/utils/api";

const Home: NextPage = (props) => {
  console.log(props);

  const { data: accessories } = api.accessories.getAll.useQuery();
  const { data: products } = api.products.getAll.useQuery({});
  return (
    <>
      <Head>
        <title>BlackBeardt | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingSection products={products} />
        <SecondSection products={products} />
        <Categories />
        <Discover products={products} />
        <LaptopsSwiper products={products} />
        <AccessoriesSwiper accessories={accessories} />
        <Marketing />
      </main>
    </>
  );
};

export default Home;
