import { type NextPage } from "next";
import Head from "next/head";
import AccessoriesSwiper from "./AccessoriesSwiper";
import Cart from "~/components/Cart";
import Categories from "./Categories";
import Discover from "./Discover";
import LandingSection from "./LandingSection";
import LaptopsSwiper from "./LaptopsSwiper";
import Marketing from "./Marketing";
import SecondSection from "./SecondSection";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>BlackBeardt | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingSection />
        <Cart />
        <SecondSection />
        <Categories />
        <Discover />
        <LaptopsSwiper />
        <AccessoriesSwiper />
        <Marketing />
      </main>
    </>
  );
};

export default Home;
